# First remove all keybindings
# unbind-key -a

# Reinsert all the regular tmux keys

bind R source-file ~/.config/tmux/tmux.conf
bind ^X lock-server
bind ^C new-window -c "$HOME"
bind ^D detach

bind S choose-session

bind * list-clients
bind ^L refresh-client
bind l refresh-client

bind : command-prompt
bind r command-prompt "rename-window '%%'"
bind K send-keys "clear"\; send-keys "Enter"
bind-key -T copy-mode-vi v send-keys -X begin-selection

bind ^A last-window
bind w list-windows
bind '"' choose-window

bind H previous-window
bind L next-window
bind l split-window
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

bind z resize-pane -Z
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r -T prefix , resize-pane -L 10
bind -r -T prefix . resize-pane -R 10
bind -r -T prefix - resize-pane -D 2
bind -r -T prefix = resize-pane -U 2

bind * setw synchronize-panes
bind P set pane-border-status
bind c kill-pane
bind x swap-pane -D
