# Reset and load custom keybindings
source-file ~/.config/tmux/tmux.reset.conf

# Terminal and general settings
set -g mouse on
set -g prefix C-a
set -g base-index 1
set -g detach-on-destroy off
set -g extended-keys on
set -g extended-keys-format csi-u
set -sg escape-time 10
set -g escape-time 50
set -g history-limit 1000000
set -g renumber-windows on
set -g set-clipboard on
set -g status-position top
setw -g mode-keys vi

# Theme
source-file ~/.config/tmux/vague.conf

# TPM plugins 
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'MunifTanjim/tmux-mode-indicator'

# PLugin configurations
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'
set -g @resurrect-strategy-nvim 'session'

# Initialize TPM (must be last)
run '~/.config/tmux/plugins/tpm/tpm'
